### PR TITLE
Pt172 33

### PR DESCRIPTION
**Pull request by Cesarceronmanrique**
Files corresponding to DAGs are loaded without queries.

### CODE REVIEW

**Comment by fgpalacios** [comment]
Favor de poner la carpeta dags en minúsculas.
Error en dags la libreria es **datetime**:
[error DAG Import Errors (2)](http://localhost:8080/home?search=etl#alerts)
Broken DAG: [/home/fgpalacios/Documents/fpalacios/code/alkemy/airflow/OT172-python/DAGs/etl_university1.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fgpalacios/Documents/fpalacios/code/alkemy/airflow/OT172-python/DAGs/etl_university1.py", line 1, in <module>
    from datatime import datatime, timedelta
ModuleNotFoundError: No module named 'datatime'

**Comment by fgpalacios** [comment]
Sigue con el mismo error 
Broken DAG: [/home/fgpalacios/Documents/fpalacios/code/alkemy/airflow/OT172-python/dags/etl_university1.py] Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fgpalacios/Documents/fpalacios/code/alkemy/airflow/OT172-python/dags/etl_university1.py", line 1, in <module>
    from datatime import datetime, timedelta
ModuleNotFoundError: No module named 'datatime'

Es datetime 

**from datetime import datetime, timedelta**

**Comment by fgpalacios** [comment]
Tienes error ahora con los operators, usa:

from airflow.providers.postgres.operators.postgres import PostgresOperator
from airflow.operators.python import PythonOperator
from airflow.operators.dummy_operator import DummyOperator

**Comment by fgpalacios** [comment]
Broken DAG: [/home/fgpalacios/Documents/fpalacios/code/alkemy/airflow/OT172-python/dags/etl_university1.py] Traceback (most recent call last):
  File "/home/fgpalacios/Documents/fpalacios/code/alkemy/airflow/OT172-python/dags/etl_university1.py", line 26, in <module>
    dag = dag
  File "/home/fgpalacios/.pyenv/versions/3.7-dev/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['sql'] is required

**Comment by Cesarceronmanrique** [comment]
Ya realicé las correcciones del operator, de igual forma le cambié el nombre a los archivos como se recomendó en la reunión de esta mañana.

**Pull request merged**
